CREATE DATABASE INGESTION;
CREATE DATABASE PROD_PROMOTE_TABLES;
CREATE DATABASE PROD_RUN_TABLES;
CREATE DATABASE STATUS;
CREATE DATABASE STATUS_TEST;
CREATE DATABASE TEST_PROMOTE_TABLES;
CREATE DATABASE TEST_RUN_TABLES;
CREATE DATABASE DELIVERABLE_OUTPUT;